### ISSUE TITLE
Gui not updating

### ISSUE THREAD

**Issue by Macfhearguis** [DomNomNomVR/cvr-audio-link#1]
The lines around the sliders at the top do not move when you move the sliders.

The sliders in question is 
Slider_X0 , Slider_X1 , Slider_X2 , Slider_X3
Slider_Threshold0 , Slider_Threshold1 , Slider_Threshold2 , Slider_Threshold3

They do not update the shader in SpectrumUI to correspond whit where the sliders are.

**Comment by DomNomNomVR** [comment]
Looking into this at the moment. 
Looks like the `mat_AudioLinkSpectrumUI` also needs to be updated, not just the `mat_AudioLink`.

**Comment by DomNomNomVR** [comment]
I've pushed a fix to this to master; probably going to release it once I've looked into the other issue too.
