### ISSUE TITLE
Doesn't include the AudioLinkAvatar Prefab

### ISSUE THREAD

**Issue by bizzclaw** [DomNomNomVR/cvr-audio-link#3]
This should really just be a goto resource for adding audiolink to anything, including avatars. Why is the AvatarPrefab missing?

**Comment by DomNomNomVR** [comment]
Thanks for the report - I'll be looking into this today

**Comment by DomNomNomVR** [comment]
@bizzclaw the newest release should include functionality for that under Tools > AudioLinkEditor
let me know how that goes

**Comment by bizzclaw** [comment]
Wow, that's actually really amazing. Thank you!
