### ISSUE TITLE
UI Spectrum and Theme colour grid not rendering in right eye [Unity 2021 - CVR] 

### ISSUE THREAD

**Issue by NovaVoidHowl** [DomNomNomVR/cvr-audio-link#4]
Following the upgrade to unity 2021.3.23f1 the Audiolink tablet no longer renders the Theme Colours grid or the Spectrum UI in the right eye.

_Example of issue_
![image](https://github.com/DomNomNomVR/cvr-audio-link/assets/31048789/8f01d1be-d454-45ad-b111-5b77fe8e792b)

This can seemingly be solved by adding in a few constants per 
<https://discord.com/channels/410126604237406209/766086942005526579/1075090431760674869>
this did work for me when I tried it.

![image](https://github.com/DomNomNomVR/cvr-audio-link/assets/31048789/3d9b815d-381f-499e-87e1-f650d8248e04)

Not sure if there is a better/more elegant way of fixing it, as I know very little about shaders code, but please find attached the 'fixed' (using that method) files for those 2 elements

(had to zip as github would not let me attach '.shader' files)
[Shader.zip](https://github.com/DomNomNomVR/cvr-audio-link/files/12207415/Shader.zip)

**Comment by DomNomNom** [comment]
Thank you for reporting - I'll be looking into this as soon as I'm able

**Comment by DomNomNomVR** [comment]
Alrighty, I've pushed a release with a fix: https://github.com/DomNomNomVR/cvr-audio-link/releases/tag/0.3.2
Could you please confirm whether that fixes all the issues seen?

**Comment by NovaVoidHowl** [comment]
Just tried it out on my test world now, seems to have sorted it, thanks for the fix 

![image](https://github.com/DomNomNomVR/cvr-audio-link/assets/31048789/eaf2c37b-450a-4414-851e-2564765a5e78)
![image](https://github.com/DomNomNomVR/cvr-audio-link/assets/31048789/17ef6844-dca6-4a79-956e-c5aa2e96eb8c)
![image](https://github.com/DomNomNomVR/cvr-audio-link/assets/31048789/62dbd9ae-6b1a-4785-b569-54d0f6ad85ea)

**Comment by DomNomNom** [comment]
:D
