### ISSUE TITLE
Audio Link Editor not playing audio

### ISSUE THREAD

**Issue by glados1235** [DomNomNomVR/cvr-audio-link#6]
When trying to use the AL test tool it throws [theses ](https://pastebin.com/ysLypHVS) 2 errors.
no audio is played but the visual side still seems to work with the audio file given, just doesn't play anything.
it does this in a new normal project with Poi and the CCK inside the included test scene

![9bb5a712d209808db642825f0057cdd4](https://github.com/user-attachments/assets/1ee90ebe-310d-4584-a165-72b9bbbceb4c)

**Comment by Macfhearguis** [comment]
it seams to me that your audio in the editor is muted.
![image](https://github.com/user-attachments/assets/d7913872-dca8-43d5-9586-be04e024fa34)

**Comment by glados1235** [comment]
yes, that is true prob should have had it on when I took the screenshot, I keep it off 90% of the time. idk if that's the cause as it has the same error with it on and continues not to work.

![3dea76234bf8bd1de0a51ef25e4cf1ac](https://github.com/user-attachments/assets/71874471-872f-4260-ae31-8da622079a73)

**Comment by DomNomNomVR** [comment]
Heya, I'll be looking into this today. most likely a issue with the script being built for a different version of unity. Could you let me know which version of CVRAudioLink and Unity you're using?

**Comment by DomNomNomVR** [comment]
Note that version [0.3.3](https://github.com/DomNomNomVR/cvr-audio-link/releases/tag/0.3.3) fixes a problem that looks just like this. I just saw that it was released but not marked as the latest release; just fixed that.

**Comment by glados1235** [comment]
> Heya, I'll be looking into this today. most likely a issue with the script being built for a different version of unity. Could you let me know which version of CVRAudioLink and Unity you're using?

i was using AudioLink-CVR-0.3.2 on Unity 2021.3.23f1
I will try the new version to see if that works

Edit: same result with 0.3.3
![image](https://github.com/user-attachments/assets/be6fdf82-671e-4dd0-947a-813214a82fb7)

**Comment by DomNomNomVR** [comment]
Heya, I've just made a release that this fix this. Could you try https://github.com/DomNomNomVR/cvr-audio-link/releases/tag/0.3.4 and let me know if that works for you?

**Comment by glados1235** [comment]
i get the same error.
what could be causing this error? I've looked over the code but I didn't get it, I wonder if it is a filesystem issue.
if you have any troubleshooting ideas, shoot them my way and I can give them a try

**Comment by DomNomNomVR** [comment]
hmm, did you install the full version? the minimal version doesn't come with the editor script. 

Is the error still coming from line 310?

**Comment by glados1235** [comment]
Yes i used the Full package, also yes still from 310

**Comment by DomNomNomVR** [comment]
odd. Your editor script should look like this: 
https://github.com/DomNomNomVR/cvr-audio-link/blob/4e44cd479e8cc4879efb8d97dd56cf9f7580b79c/AudioLink/EditorScript/AudioLinkEditor.cs

I've checked that 0.3.4 contains the file like that. The new file has less than 300 lines so something must be off on your end. Maybe double check the setup and restart unity

**Comment by glados1235** [comment]
i made sure to remove everything and use the new file, so I'm really not sure. let me go over and clean it again and see

**Comment by glados1235** [comment]
Okay, so yea unity was being weird then, I deleted the AL folder just like I did before and installed the new version and it had the correct line count, issue was fixed. this is why I never trust unity lol.

good fix though thanks!
